### ISSUE TITLE
Can't resolve '@/styles/globals.css/' for Next.js 14.2.5

### ISSUE THREAD

**Issue by EthanL06** [diragb/shadcn-dropzone#1]
![image](https://github.com/user-attachments/assets/9ad0a7f1-44b9-44b2-af0d-19cfd65ead49)

Built my Next.js project using `npx create-next-app@latest`.

Getting the error because when the project is built, the `globals.css` file is created under the `app` folder instead of `styles` which the package seems to be using. Manually changing the import within the node module or moving `globals.css` to its own `styles` folder doesn't seem to work.

**Comment by diragb** [comment]
Fixed in [v0.2.1](https://www.npmjs.com/package/shadcn-dropzone) - thanks for reporting this bug.
